version: "3.7"
services:
    mq:
        image: redis
        deploy:
            placement:
                constraints:
                  - node.role == manager
            update_config:
                parallelism: 1
                delay: 3s
        volumes:
          # - /nfs/pyromancer/Projects/PBA/redis/data:/data
          - /media/tony/Seagate6TB_ext4/data/dssplay/redis/:/data
        ports:
          - 6381:6379
        networks:
          - dss-network

    app:
        image: anthonyrawlinsuom/dssplay
        ports:
          - 4040:4040
        environment:
          - PG_USER=postgres
          - PG_HOST=postgreserver
          - PG_PASSWORD=secret
          - PG_DATABASE=postgres
          - PG_PORT=5432
          - PROTOCOL=https
          - WEB=dss.lightning.deepblack.cloud
        networks:
            - staging-network
            - dss-network
        deploy:
            placement:
                constraints:
                  # - node.role == manager
                  - node.hostname == deepblack
                  # - node.labels.NFS == attached
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.dssplay.rule=Host(`www.dssplay.lightning.deepblack.cloud`)"
              - "traefik.http.routers.dssplay.entrypoints=web-secured"
              - "traefik.http.routers.dssplay.tls.certresolver=letsencryptresolver"
              - "traefik.http.services.dssplay.loadbalancer.server.port=4040"
              - "traefik.http.services.dssplay.loadbalancer.passhostheader=true"
              - "traefik.docker.network=staging-network"

    postgreserver:
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=secret
          - PGPASSWORD=secret
          - POSTGRES_DB=postgres
          - PGDATA=/data/postgres
        volumes:
          - /media/tony/Seagate6TB_ext4/data/dssplay/postgres:/data/postgres
        networks:
          - dss-network
        ports:
          - "5432:5432"

    # pgloader:
    #     # image: anthonyrawlinsuom/loader
    #     image: dimitri/pgloader
    #     command: ["pgloader --version"]
    #     networks:
    #       - dss-network

        # volumes:
        #     - /media/tony/Seagate6TB_ext4/Current/DSS/DSS-data/:/tmp/

    pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=sense@icloud.com
          - PGADMIN_DEFAULT_PASSWORD=secret
        ports:
            - "5050:80"
        volumes:
          - /media/tony/Seagate6TB_ext4/data/dssplay/pgadmin:/root/.pgadmin
        networks:
          - dss-network
          - staging-network
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                  # - node.role == manager
                  - node.hostname == deepblack
            labels:
              - "traefik.enable=true"
              - "traefik.http.routers.postgres.rule=Host(`pgadmin.dssplay.lightning.deepblack.cloud`)"
              - "traefik.http.routers.postgres.entrypoints=web-secured"
              - "traefik.http.routers.postgres.tls.certresolver=letsencryptresolver"
              - "traefik.http.services.postgres.loadbalancer.server.port=80"
              - "traefik.http.services.postgres.loadbalancer.passhostheader=true"
              - "traefik.docker.network=staging-network"

networks:
    dss-network:
        driver: overlay
        attachable: true
    staging-network:
        external: true
